# Generated by Django 4.2.20 on 2025-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='property',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
