# Generated by Django 4.2.20 on 2025-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_amenity_options_amenity_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='main_app.amenity'),
        ),
    ]
